import { createContext, useContext, useState, useEffect } from 'react';

// ─────────────────────────────────────────
//  TRANSLATIONS
// ─────────────────────────────────────────
const translations = {
  en: {
    // Language select
    chooseLanguage: 'Choose Your Language',
    languageSubtitle: 'Select the language you prefer to use the system',

    // Role select
    appName: 'CommSave',
    appSubtitle: 'Community Saving System',
    whoAreYou: 'Who are you? Choose your role to continue',
    manager: 'Manager',
    member: 'Member',
    managerDesc: 'Full system access — manage members, approve loans, view all reports',
    memberDesc: 'View your savings, request loans, track your account activity',
    newMember: 'New member?',
    registerHere: 'Register here',

    // Login
    managerLogin: 'Manager Login',
    memberLogin: 'Member Login',
    managerPortal: 'Manager Portal',
    memberPortal: 'Member Portal',
    emailAddress: 'Email Address',
    password: 'Password',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    signInAs: 'Sign In as',
    back: 'Back',
    noAccount: "Don't have an account?",
    managerNote: 'Manager accounts are created by the system administrator.',
    loginFailed: 'Login failed. Check your credentials.',
    welcomeBack: 'Welcome back',
    notManagerAccount: 'This account is not a Manager account. Use the Member login.',
    notMemberAccount: 'This account is not a Member account. Use the Manager login.',

    // Register
    createAccount: 'Create your member account',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    phoneNumber: 'Phone Number',
    nationalId: 'National ID',
    address: 'Address',
    occupation: 'Occupation',
    emergencyContact: 'Emergency Contact Name',
    emergencyPhone: 'Emergency Contact Phone',
    nextOfKin: 'Next of Kin Name',
    relationship: 'Relationship',
    nextOfKinPhone: 'Next of Kin Phone',
    nextStep: 'Next: Personal Details →',
    createMyAccount: 'Create My Account',
    alreadyHaveAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    passwordMismatch: 'Passwords do not match',
    registrationSuccess: 'Registration successful! Please login.',
    step: 'Step',
    of: 'of',
    accountInfo: 'Account Info',
    personalDetails: 'Personal Details',

    // Dashboard
    dashboard: 'Dashboard',
    welcomeManager: 'Manager Dashboard — Full system overview',
    welcomeMember: 'Member Dashboard — Your personal account overview',
    totalMembers: 'Total Members',
    totalSavings: 'Total Savings',
    activeLoans: 'Active Loans',
    unpaidPenalties: 'Unpaid Penalties',
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions yet',
    quickOverview: 'Quick Overview',
    loansAwaitingApproval: 'Loans Awaiting Approval',
    totalSavingsPool: 'Total Savings Pool',
    penaltiesOutstanding: 'Penalties Outstanding',
    mySavingsBalance: 'My Savings Balance',
    pendingLoans: 'Pending Loans',
    awaitingApproval: 'Awaiting approval',
    loanRepaymentDue: 'Loan Repayment Due',
    penaltiesOutstandingAlert: 'Penalties Outstanding',
    payNow: 'Pay Now',
    recentSavings: 'Recent Savings',
    myLoans: 'My Loans',
    noSavingsYet: 'No savings records yet',
    noLoansFound: 'No loans found',

    // Navigation
    members: 'Members',
    savings: 'Savings',
    loans: 'Loans',
    penalties: 'Penalties',
    attendance: 'Attendance',
    accounting: 'Accounting',
    reports: 'Reports',
    settings: 'Settings',
    auditTrail: 'Audit Trail',
    logout: 'Logout',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    add: 'Add',
    submit: 'Submit',
    approve: 'Approve',
    reject: 'Reject',
    pay: 'Pay',
    loading: 'Loading...',
    noRecords: 'No records found',
    actions: 'Actions',
    status: 'Status',
    amount: 'Amount',
    date: 'Date',
    notes: 'Notes',
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    completed: 'Completed',
    all: 'All',
    paid: 'Paid',
    unpaid: 'Unpaid',

    // Settings
    monthlyContribution: 'Monthly Contribution Amount',
    interestRate: 'Loan Interest Rate',
    absencePenalty: 'Absence Penalty Amount',
    latePaymentPenalty: 'Late Payment Penalty',
    maxLoanMultiplier: 'Max Loan Multiplier (× savings)',
    groupName: 'Group Name',
    currency: 'Currency',
    initializeSettings: 'Initialize Settings',
    resetDefaults: 'Reset to Defaults',
  },

  rw: {
    // Language select
    chooseLanguage: 'Hitamo Ururimi',
    languageSubtitle: 'Hitamo ururimi ushaka gukoresha sisitemu',

    // Role select
    appName: 'CommSave',
    appSubtitle: 'Sisitemu yo Gucunga Amafaranga',
    whoAreYou: 'Uri nde? Hitamo uruhare rwawe kugira ngo ukomeze',
    manager: 'Umuyobozi',
    member: 'Umunyamuryango',
    managerDesc: 'Uburenganzira bwose — gucunga abanyamuryango, kwemera inguzanyo, kureba raporo zose',
    memberDesc: 'Reba amafaranga yawe, saba inguzanyo, kurikirana konti yawe',
    newMember: 'Umunyamuryango mushya?',
    registerHere: 'Iyandikishe hano',

    // Login
    managerLogin: 'Kwinjira nk\'Umuyobozi',
    memberLogin: 'Kwinjira nk\'Umunyamuryango',
    managerPortal: 'Inzira y\'Umuyobozi',
    memberPortal: 'Inzira y\'Umunyamuryango',
    emailAddress: 'Imeyili',
    password: 'Ijambo ry\'ibanga',
    signIn: 'Injira',
    signingIn: 'Birinjira...',
    signInAs: 'Injira nka',
    back: 'Subira',
    noAccount: 'Nta konti ufite?',
    managerNote: 'Konti z\'abayobozi zikorwa n\'umuyobozi w\'inkuru.',
    loginFailed: 'Kwinjira byanze. Reba imeyili n\'ijambo ry\'ibanga.',
    welcomeBack: 'Murakaza neza',
    notManagerAccount: 'Iyi konti si iya Umuyobozi. Koresha inzira y\'Umunyamuryango.',
    notMemberAccount: 'Iyi konti si iya Umunyamuryango. Koresha inzira y\'Umuyobozi.',

    // Register
    createAccount: 'Fungura konti y\'umunyamuryango',
    fullName: 'Amazina yuzuye',
    confirmPassword: 'Emeza ijambo ry\'ibanga',
    phoneNumber: 'Numero ya telefone',
    nationalId: 'Indangamuntu',
    address: 'Aho utuye',
    occupation: 'Akazi',
    emergencyContact: 'Izina ry\'uwo wahamagara mu bihe bikomeye',
    emergencyPhone: 'Telefone y\'uwo wahamagara mu bihe bikomeye',
    nextOfKin: 'Izina ry\'umuryango wawe',
    relationship: 'Isano',
    nextOfKinPhone: 'Telefone y\'umuryango wawe',
    nextStep: 'Komeza: Amakuru bwite →',
    createMyAccount: 'Fungura Konti Yanjye',
    alreadyHaveAccount: 'Usanzwe ufite konti?',
    signInHere: 'Injira hano',
    passwordMismatch: 'Amagambo y\'ibanga ntahuye',
    registrationSuccess: 'Iyandikisha ryakunze! Injira.',
    step: 'Intambwe',
    of: 'kuri',
    accountInfo: 'Amakuru ya Konti',
    personalDetails: 'Amakuru Bwite',

    // Dashboard
    dashboard: 'Imbonerahamwe',
    welcomeManager: 'Imbonerahamwe y\'Umuyobozi — Incamake y\'isi yose',
    welcomeMember: 'Imbonerahamwe y\'Umunyamuryango — Incamake ya konti yawe',
    totalMembers: 'Abanyamuryango bose',
    totalSavings: 'Amafaranga yose yabitswe',
    activeLoans: 'Inguzanyo zikoreshwa',
    unpaidPenalties: 'Amahazabu atishyuwe',
    recentTransactions: 'Ibikorwa bya vuba',
    noTransactions: 'Nta bikorwa bihari',
    quickOverview: 'Incamake Yihuse',
    loansAwaitingApproval: 'Inguzanyo zitegereje kwemezwa',
    totalSavingsPool: 'Amafaranga yose yabitswe',
    penaltiesOutstanding: 'Amahazabu asigaye',
    mySavingsBalance: 'Amafaranga yanjye yabitswe',
    pendingLoans: 'Inguzanyo zitegereje',
    awaitingApproval: 'Itegereje kwemezwa',
    loanRepaymentDue: 'Inguzanyo igomba kwishyurwa',
    penaltiesOutstandingAlert: 'Amahazabu asigaye',
    payNow: 'Ishyura Ubu',
    recentSavings: 'Amafaranga yabitswe vuba',
    myLoans: 'Inguzanyo Zanjye',
    noSavingsYet: 'Nta mafaranga yabitswe',
    noLoansFound: 'Nta nguzanyo zibonetse',

    // Navigation
    members: 'Abanyamuryango',
    savings: 'Amafaranga Yabitswe',
    loans: 'Inguzanyo',
    penalties: 'Amahazabu',
    attendance: 'Ubwitabire',
    accounting: 'Ibaruramari',
    reports: 'Raporo',
    settings: 'Igenamiterere',
    auditTrail: 'Inzira y\'Igenzura',
    logout: 'Sohoka',

    // Common
    save: 'Bika',
    cancel: 'Reka',
    delete: 'Siba',
    edit: 'Hindura',
    view: 'Reba',
    add: 'Ongeraho',
    submit: 'Ohereza',
    approve: 'Emeza',
    reject: 'Tangira',
    pay: 'Ishyura',
    loading: 'Birashakwa...',
    noRecords: 'Nta makuru abonetse',
    actions: 'Ibikorwa',
    status: 'Imiterere',
    amount: 'Amafaranga',
    date: 'Itariki',
    notes: 'Ibisobanuro',
    active: 'Bikoreshwa',
    inactive: 'Bitikoreshwa',
    pending: 'Bitegereje',
    completed: 'Byarangiye',
    all: 'Byose',
    paid: 'Byishyuwe',
    unpaid: 'Bitishyuwe',

    // Settings
    monthlyContribution: 'Umusanzu wa buri kwezi',
    interestRate: 'Inyungu z\'inguzanyo (%)',
    absencePenalty: 'Ihazabu ry\'kutabaho',
    latePaymentPenalty: 'Ihazabu ry\'kwishyura guhera',
    maxLoanMultiplier: 'Inguzanyo nini (× amafaranga yabitswe)',
    groupName: 'Izina ry\'itsinda',
    currency: 'Ifaranga',
    initializeSettings: 'Tangira Igenamiterere',
    resetDefaults: 'Subira ku makuru ya mbere',
  },

  sw: {
    // Language select
    chooseLanguage: 'Chagua Lugha',
    languageSubtitle: 'Chagua lugha unayopendelea kutumia mfumo',

    // Role select
    appName: 'CommSave',
    appSubtitle: 'Mfumo wa Akiba ya Jamii',
    whoAreYou: 'Wewe ni nani? Chagua jukumu lako kuendelea',
    manager: 'Meneja',
    member: 'Mwanachama',
    managerDesc: 'Ufikiaji kamili — simamia wanachama, idhinisha mikopo, angalia ripoti zote',
    memberDesc: 'Angalia akiba yako, omba mkopo, fuatilia shughuli za akaunti yako',
    newMember: 'Mwanachama mpya?',
    registerHere: 'Jisajili hapa',

    // Login
    managerLogin: 'Kuingia kama Meneja',
    memberLogin: 'Kuingia kama Mwanachama',
    managerPortal: 'Mlango wa Meneja',
    memberPortal: 'Mlango wa Mwanachama',
    emailAddress: 'Anwani ya Barua Pepe',
    password: 'Nywila',
    signIn: 'Ingia',
    signingIn: 'Inaingia...',
    signInAs: 'Ingia kama',
    back: 'Rudi',
    noAccount: 'Huna akaunti?',
    managerNote: 'Akaunti za wasimamizi zinaundwa na msimamizi wa mfumo.',
    loginFailed: 'Kuingia kumeshindwa. Angalia barua pepe na nywila yako.',
    welcomeBack: 'Karibu tena',
    notManagerAccount: 'Akaunti hii si ya Meneja. Tumia mlango wa Mwanachama.',
    notMemberAccount: 'Akaunti hii si ya Mwanachama. Tumia mlango wa Meneja.',

    // Register
    createAccount: 'Fungua akaunti ya mwanachama',
    fullName: 'Jina Kamili',
    confirmPassword: 'Thibitisha Nywila',
    phoneNumber: 'Nambari ya Simu',
    nationalId: 'Kitambulisho cha Taifa',
    address: 'Anwani',
    occupation: 'Kazi',
    emergencyContact: 'Jina la Mtu wa Dharura',
    emergencyPhone: 'Simu ya Mtu wa Dharura',
    nextOfKin: 'Jina la Ndugu wa Karibu',
    relationship: 'Uhusiano',
    nextOfKinPhone: 'Simu ya Ndugu wa Karibu',
    nextStep: 'Ifuatayo: Maelezo Binafsi →',
    createMyAccount: 'Fungua Akaunti Yangu',
    alreadyHaveAccount: 'Una akaunti tayari?',
    signInHere: 'Ingia hapa',
    passwordMismatch: 'Nywila hazifanani',
    registrationSuccess: 'Usajili umefanikiwa! Tafadhali ingia.',
    step: 'Hatua',
    of: 'ya',
    accountInfo: 'Maelezo ya Akaunti',
    personalDetails: 'Maelezo Binafsi',

    // Dashboard
    dashboard: 'Dashibodi',
    welcomeManager: 'Dashibodi ya Meneja — Muhtasari wa mfumo wote',
    welcomeMember: 'Dashibodi ya Mwanachama — Muhtasari wa akaunti yako',
    totalMembers: 'Jumla ya Wanachama',
    totalSavings: 'Jumla ya Akiba',
    activeLoans: 'Mikopo Inayoendelea',
    unpaidPenalties: 'Faini Ambazo Hazijalipwa',
    recentTransactions: 'Miamala ya Hivi Karibuni',
    noTransactions: 'Hakuna miamala bado',
    quickOverview: 'Muhtasari wa Haraka',
    loansAwaitingApproval: 'Mikopo Inayosubiri Idhini',
    totalSavingsPool: 'Jumla ya Akiba',
    penaltiesOutstanding: 'Faini Zilizobaki',
    mySavingsBalance: 'Salio la Akiba Yangu',
    pendingLoans: 'Mikopo Inayosubiri',
    awaitingApproval: 'Inasubiri idhini',
    loanRepaymentDue: 'Malipo ya Mkopo Yanastahili',
    penaltiesOutstandingAlert: 'Faini Zilizobaki',
    payNow: 'Lipa Sasa',
    recentSavings: 'Akiba ya Hivi Karibuni',
    myLoans: 'Mikopo Yangu',
    noSavingsYet: 'Hakuna rekodi za akiba bado',
    noLoansFound: 'Hakuna mikopo iliyopatikana',

    // Navigation
    members: 'Wanachama',
    savings: 'Akiba',
    loans: 'Mikopo',
    penalties: 'Faini',
    attendance: 'Mahudhurio',
    accounting: 'Uhasibu',
    reports: 'Ripoti',
    settings: 'Mipangilio',
    auditTrail: 'Rekodi ya Ukaguzi',
    logout: 'Toka',

    // Common
    save: 'Hifadhi',
    cancel: 'Ghairi',
    delete: 'Futa',
    edit: 'Hariri',
    view: 'Angalia',
    add: 'Ongeza',
    submit: 'Wasilisha',
    approve: 'Idhinisha',
    reject: 'Kataa',
    pay: 'Lipa',
    loading: 'Inapakia...',
    noRecords: 'Hakuna rekodi zilizopatikana',
    actions: 'Vitendo',
    status: 'Hali',
    amount: 'Kiasi',
    date: 'Tarehe',
    notes: 'Maelezo',
    active: 'Inafanya kazi',
    inactive: 'Haifanyi kazi',
    pending: 'Inasubiri',
    completed: 'Imekamilika',
    all: 'Yote',
    paid: 'Imelipwa',
    unpaid: 'Haijalipiwa',

    // Settings
    monthlyContribution: 'Kiasi cha Mchango wa Kila Mwezi',
    interestRate: 'Kiwango cha Riba ya Mkopo (%)',
    absencePenalty: 'Faini ya Kutokuwepo',
    latePaymentPenalty: 'Faini ya Malipo ya Kuchelewa',
    maxLoanMultiplier: 'Kizidishio cha Mkopo wa Juu (× akiba)',
    groupName: 'Jina la Kikundi',
    currency: 'Sarafu',
    initializeSettings: 'Anzisha Mipangilio',
    resetDefaults: 'Rudisha Mipangilio ya Awali',
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('css_language') || null; // null = not chosen yet
  });

  const changeLanguage = (lang) => {
    localStorage.setItem('css_language', lang);
    setLanguage(lang);
  };

  const t = (key) => {
    if (!language) return translations.en[key] || key;
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export { translations };
